apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devopsbatches.trainwithshubham.com
spec:
  group: trainwithshubham.com
  scope: Namespaced
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevopsBatch
    shortNames:
      - junoon
      - batches
      - tws
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "This is the name of devops batch"
                duration:
                  type: string
                  description: "This is the duration of the devops batch"
                mode:
                  type: string
                  description: "This is the mode of the batch eg. Live/Recorded"
                platform:
                  type: string
                  description: "This is the platform of the batch"

