kind: Pod
apiVersion: v1
metadata:
  name: side-test
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: main-container # Produce Logs
      image: busybox:latest
      command: ["sh", "-c", "while true; do echo 'Hello DOSTON' >> /var/log/app.log; sleep 5; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/

    - name: sidecar-container # Display Logs
      image: busybox:latest
      command: ["sh", "-c", "tail -f /var/log/app.log"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/

